#!/bin/sh

# chkconfig: 2345 20 80
# description: iPlant Job Execution Service

. /etc/init.d/functions

################################################################################
# Specific script configuration
# Change these as needed to run a specific nodejs program.
################################################################################
RUNUSER=condor

program=iplant-jobexec
script=/usr/local/lib/node/jobexec/jobexec.js
conf=/etc/iplant-jobexec.conf
NODE_PATH_EXTRAS=/usr/local/lib/node/jobexec
################################################################################

################################################################################
# Generic paths
# None of these should need to be changed to execute a nodejs script unless 
# there is specific configuration that is needed for the script.
################################################################################
launch=/usr/local/bin/node-launch.py
node=/usr/local/bin/node
piddir=/var/run/$program
pidfile=/var/run/$program/$program.pid
lockfile=/var/lock/subsys/$program
logdir=/var/log/$program
RETVAL=0

start () {
    echo -n $"Starting $program: "
    
    # Make a dir for the  pid file
    mkdir -p $piddir
    chown $RUNUSER:$RUNUSER $piddir

    mkdir -p $logdir
    chown $RUNUSER:$RUNUSER $logdir

    NODE_PATH=$NODE_PATH:/usr/local/lib/node:$NODE_PATH_EXTRAS
    runuser -s /bin/bash -l $RUNUSER -c "NODE_PATH=${NODE_PATH} ${launch} ${node} ${script} ${conf} ${pidfile}"
    RETVAL=$?

    [ $RETVAL = 0 ] && success && touch ${lockfile}
    [ $RETVAL -ne 0 ] && failure
    echo

    return $RETVAL
}

stop () {
    echo -n $"Stopping $program: "
    killproc -p ${pidfile}
    RETVAL=$?
    echo
    [ $RETVAL = 0 ] && rm -rf ${lockfile} ${piddir}
}

restart () {
    echo -n $"Restarting $program: "
    stop
    start
}

showstatus () {
    status -p ${pidfile} ${program}
    RETVAL=$?
}

case "$1" in
    start)
        start
    ;;
    
    stop)
        stop
    ;;
    
    restart)
        restart
    ;;
    
    status)
        showstatus
    ;;
    
    *)
        echo "Usage: $program {start|stop|restart,status}"
        exit 1
    ;;
esac

exit $RETVAL
